services:
  frontend:
    build: ./frontend
    container_name: dashboard_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: dashboard_backend
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
